### ISSUE TITLE
C stack usage  17723277 is too close to the limit

### ISSUE THREAD

**Issue by KateK** [hartleys/JunctionSeq#11]
I've tried to run JunctionSeqAnalyses on my data and I get this issue, so I enlarged stack limit, but it didn't help. I am wondering if that function cost so much memory or am I doing something wrong... Did you meet this issue earlier?

**Comment by hartleys** [comment]
A few questions:
- How many samples do you have?
- What species?
- How many cores are you using (via the nCores parameter)? More cores increases the memory requirements.
- How much memory are you giving it?
- What operating system are you using?
- What hardware are you using? Is this a cluster? A high performance server? A workstation? A laptop?
- How much memory does the computer have?

**Comment by hartleys** [comment]
Also: could you post the output log?

**Comment by KateK** [comment]
- I have 4 samples (2 controls, 2 treated)
- Homo Sapiens (annotation file downloaded from Ensembl and converted with QoRTs to flat GFF)
- I use 1 core
- I changed stack limit to 16 megs with ulimit bash function
- Ubuntu 15.04
- workstation 
- 32 GB

I can post the output log but on Mondey when i get back to my work :-)

**Comment by KateK** [comment]
Ok, I think that I solved this problem with changing ulimits like this (ulimit -m 124380, ulimit -s unlimited, ulimit -d unlimited). Now I have an error like this. Could you help me to figure it out?
 `-----> reading annotation...
Błąd w poleceniu 'read.table(file = file, header = header, sep = sep, quote = quote, ':
  'file' must be a character string or connection
Wywołania: runJunctionSeqAnalyses ... readJunctionSeqCounts -> readAnnotationData -> read.delim -> read.table
Wykonywanie wstrzymane`

**Comment by hartleys** [comment]
What language is that? What does it say?

Can you post the command you used? It looks like you're not setting a decoder file?

**Comment by KateK** [comment]
Sorry I didn't noticed that there are some words in Polish :-). You're right there was a problem with decoder file (I had a quotes in names of columns). Now it's ok, but I have another problem with making plots. When I use function buildAllPlots everything in console seems to be ok, but all plots are without any data. 
![30-normcts](https://cloud.githubusercontent.com/assets/5678468/16916229/1288ba10-4cfc-11e6-99ce-eb1d5c88c49d.png)

**Comment by hartleys** [comment]
This is a bizarre bug. Can you post the commands you used to run the analysis and create this plot?

Note that there's actually a significant exon, which implies that it's not just an empty dataset. It's almost as if it's drawing white (or transparent) lines for the data.

**Comment by KateK** [comment]
I figured it out. It was about semi-transparency. I created plots with cairo package and now everything is ok. Thank you for Your time. I am really appreciated 😊. 

Kate

Dnia 18.07.2016 o godz. 16:18 hartleys notifications@github.com napisał(a):
