### ISSUE TITLE
buildAllPlotsForGene unable to create new directories

### ISSUE THREAD

**Issue by hobrien** [hartleys/JunctionSeq#13]
Hi,

Thanks for writing this package. It looks like exactly what we need to deal with novel splice sites in our DEXseq analyses. I've encountered a couple of extremely minor issues that I thought I'd bring to your attention (I'll post them separately). 

The second problem is that if I use a non-existent directory in the prefix for buildAllPlotsForGene, it dies with a pretty ugly error message. With buildAllPlots, it happily creates a new directory. It would probably save some confusion if this behavior could be harmonized.

**Comment by hartleys** [comment]
Easily fixed. It'll be in the next release.

**Comment by hartleys** [comment]
You mentioned you ran into other issues? If you point them out I can fix them all in one release.

Or was it just these two?

**Comment by hobrien** [comment]
Just these two. Worked a trick otherwise

**Comment by hartleys** [comment]
Fixed in the new release (v1.3.5). I also added an error message when the parent directory doesn't exist.
