### ISSUE TITLE
error about fitDisp

### ISSUE THREAD

**Issue by aiminy** [hartleys/JunctionSeq#17]
I am using runJunctionSeqAnalyses function, but I got the following error liking this:
Error in fitDisp(ySEXP = ySEXP, xSEXP = xSEXP, mu_hatSEXP = mu_hatSEXP, :
not compatible with requested type

Do you any idea about this?

Aimin

**Comment by hartleys** [comment]
It looks like this is an issue with the devel (v3.5) branch of Bioconductor. It looks like DESeq2 changed the syntax on a few of its functions.

I am aware of the issue and I'll post an update once it's done with testing.

In the meantime, I would recommend using the release version (v3.4), which should work fine.

**Comment by hartleys** [comment]
The newest release fixes this issue. It automatically checks the DESeq2 version and applies the correct function.
