### ISSUE TITLE
Comparing JunctionSeq to DEXSeq

### ISSUE THREAD

**Issue by brgew** [hartleys/JunctionSeq#19]
Hi,

I'm running DEXSeq and JunctionSeq, in the DEXSeq emulation mode, on the JctSeqData example
data set as a consistency test. I am following the description in the JunctionSeq User Manual with
the minor modification of setting the DEXSeqDataSetFromHTSeq parameter 'sampleData=design'
to 'sampleData=sampleTable' (I used the instructions in the QoRTs manual to set sampleTable). 
I find that the DEXSeq and JunctionSeq p-values are the same but the base mean and log2FC values
differ a fair amount. The user manual seems to suggest that I might see identical results so I'm
wondering whether I have reasonable expectations.

I installed Bioconductor 3.4 for this comparison so I ran DEXSeq version 1.20.2 and JunctionSeq
version 1.4.0 .

Thank you.

**Comment by hartleys** [comment]
JunctionSeq's "emulation mode" was designed to emulate an older version of DEXSeq (1.14, I believe). It matched that version exactly, but DEXSeq has changed a bit since then.
