### ISSUE TITLE
Summary Plots created by JunctionSeq

### ISSUE THREAD

**Issue by Tomoya89** [hartleys/JunctionSeq#20]
Hi, 
Thank you for your kind help in the QoRTs pages.
After I done the JunctionSeq analyses, I continued to figure out the results.

By using the command 'buildAllPlots', I know I can create a MA Plot representing how many genes are up-regulated or down-regulated. But I can't make out how to check which genes are picked up.
 Can you create a lists from this MA Plot analysis or do I have to do a DEseq2 analysis independently?
 
Thanks,
Tomoya

**Comment by hartleys** [comment]
The dots shown in the MA plots are not genes, but rather are exons or splice junctions.

You can extract the list of genes that have significant differential exon/splice-junction usage using the writeCompleteResults() function: [see here](http://hartleys.github.io/JunctionSeq/Rhtml/writeCompleteResults.html). This should output a bunch of different files, as described in [the vignette](http://hartleys.github.io/JunctionSeq/doc/JunctionSeq.pdf), see section 5.3 on pages 13-15.

These files will show the genes that have differential feature usage, and indicate which features are differentially used.

**Comment by Tomoya89** [comment]
Thank you for your kind reply.
I got the meaning of the MA plots created by JunctionSeq and I understand I have to do another analysis to know the expression of genes.
Thank you so much.
