### ISSUE TITLE
Two libraries

### ISSUE THREAD

**Issue by cwtkiwi** [hartleys/JunctionSeq#23]
Hello everyone,

I would like to know if anyone has tried to run junctionseq in small number libraries, like two? I did it because of the limitation of the sample source but the there popped up error message. Is it not allowed in Junctionseq?

**Comment by hartleys** [comment]
In general you cannot make statistical inferences comparing two individual samples. There's just no way to estimate the variability.

JunctionSeq does not provide support for such comparisons. The complexity of splice junction and exon coverage distributions and the number of factors involved means that even if you found anything, chances are it would just be junk anyways. 

You can always use QoRTs to generate "wiggle" and "splice" tracks and just visually compare them in the  UCSC genome browser. But any statistical analysis would just give false certainty. 

(see section 10.3 in the [QoRTs user manual](http://hartleys.github.io/QoRTs/doc/QoRTs-vignette.pdf)) for instructions on how to produce such files.

**Comment by cwtkiwi** [comment]
Thank you very much for your comments!
