### ISSUE TITLE
Help with interpreting the error, and way to go around it

### ISSUE THREAD

**Issue by sahilseth** [hartleys/JunctionSeq#3]
I am getting the following error from JunctionSeq, which stems from issue with estimateDispersions (I believe). This output is after using the recommended parameter (method.dispFit = "local").

```

using supplied model matrix
-----> ejsd: Dispersion estimation failed for 0 out of 396493 'testable' counting bins. Setting these features to be 'untestable'
---> FINISHED estimateJunctionSeqDispersions (Mon Nov 16 06:55:02 2015)
> rJSA: Dispersions estimated. Mon Nov 16 06:55:02 2015.
     Memory Usage:
        jscs: 943 Mb
        fData(jscs): 130.8 Mb
        pData(jscs): 9.7 Kb
        jscs@fittedMu: 330.9 Mb
        counts(jscs): 114.5 Mb
        jscs@geneCountData: 10.4 Mb
        jscs@countVectors: 186.7 Mb
        jscs@flatGffData: 208.4 Mb
        jscs@DESeqDataSet : 61.6 Mb
> rJSA: Fitting Dispersion Fcn... Mon Nov 16 06:55:08 2015.
> fitDispersionFunction() Starting (Mon Nov 16 06:55:08 2015)
>   (fitType = parametric)
>   (finalDispersionMethod = shrink)
>   (fitDispersionsForExonsAndJunctionsSeparately = TRUE)
>    fdf: Fitting dispersions:
>       (Iteration 1) Parametric Dispersion Coefs: [0.0688596034609616,0.315401296775572]
>       (Iteration 2) Parametric Dispersion Coefs: [0.0986239157896318,0.156400102406969]
>       (Iteration 3) Parametric Dispersion Coefs: [0.12345799793127,0.086911336800456]
>       (Iteration 4) Parametric Dispersion Coefs: [0.178398164606861,0.011553721990239]
Error : parametric dispersion fit failed
>    fdf: Fitting dispersions of exons and junctions to separate fitted trends.
>    fdf: Fitting exon dispersions:
>       (Iteration 1) Parametric Dispersion Coefs: [0.0536139808805315,0.432826999472707]
>       (Iteration 2) Parametric Dispersion Coefs: [0.0645434412033198,0.317688598578521]
>       (Iteration 3) Parametric Dispersion Coefs: [0.0687914737955971,0.286712544936312]
>       (Iteration 4) Parametric Dispersion Coefs: [0.0700139380668246,0.278453672742301]
>       (Iteration 5) Parametric Dispersion Coefs: [0.0703387772826443,0.276472033092631]
>       (FINAL) Parametric Dispersion Coefs: [0.0703685656436518,0.27626661272365]
>    fdf: Fitting splice-junction dispersions:
>       (Iteration 1) Parametric Dispersion Coefs: [0.10891582064228,0.165875588637397]
>       (Iteration 2) Parametric Dispersion Coefs: [0.171103339868573,0.0341692236351757]
Error : parametric dispersion fit failed
In addition: Warning message:
In adapted.estimateDispersionsFit(means = means[useForFit], disps = disps[useForFit],  :
  the parametric fit of dispersion estimates over the mean of counts
failed, which occurs when the trend is not well captured by the
function y = a/x + b. A local regression fit is automatically performed,
and the analysis can continue. You can specify fitType='local' or 'mean'
to avoid this message if re-running the same data.
When using local regression fit, the user should examine plotDispEsts(dds)
to make sure the fitted line is not sharply curving up or down based on
the position of individual points.
Warning message:
In adapted.estimateDispersionsFit(means = means[useCols], disps = disps[useCols],  :
  the parametric fit of dispersion estimates over the mean of counts
failed, which occurs when the trend is not well captured by the
function y = a/x + b. A local regression fit is automatically performed,
and the analysis can continue. You can specify fitType='local' or 'mean'
to avoid this message if re-running the same data.
When using local regression fit, the user should examine plotDispEsts(dds)
to make sure the fitted line is not sharply curving up or down based on
the position of individual points.
Error in ifelse(isExon, jscs@dispFunctionExon(means), jscs@dispFunctionJct(means)) :
  error in evaluating the argument 'no' in selecting a method for function 'ifelse': Error in preplot.locfit.raw(object, newdata, where, what, band) :
  NA/NaN/Inf in foreign function call (arg 5)
```

**Comment by hartleys** [comment]
Looks like a bug introduced in a (relatively) recent update. 

I'll fix it and add a few unit tests to prevent such things from making it through the release process again. Expect a new release by this afternoon.

**Comment by hartleys** [comment]
The newest release, v0.6.7, fixes this problem.

I am currently implementing a number of error checking and similar improvements to prevent a bug like this from sneaking through again. I'll probably release that version later tonight.

**Comment by sahilseth** [comment]
Awesome, will try this and update. 
Planning for a bioc, release?! Would be cool!

https://github.com/hartleys/JunctionSeq/blob/master/R-CMD-BiocCheck-LINUX64-R-v3.2.2.log

**Comment by hartleys** [comment]
The newest update, 0.6.9, fixes an additional problem: in the old version when you pass the "local" option to the top-level runJunctionSeqAnalysis() method, it wouldn't pass this option on to fitJunctionSeqDispersionFunction(). This is why the error managed to escape getting caught.

In any case. Fixed now.

As for bioconductor: I'm looking into it. We shall see.

**Comment by sahilseth** [comment]
I am still having a issue here:

```
>       (Iteration 4) Parametric Dispersion Coefs: [0.178398164606861,0.011553721990239]
Error : parametric dispersion fit failed
>    fdf: Fitting dispersions of exons and junctions to separate fitted trends.
>    fdf: Fitting exon dispersions:
>       (Iteration 1) Parametric Dispersion Coefs: [0.0536139808805315,0.432826999472707]
>       (Iteration 2) Parametric Dispersion Coefs: [0.0645434412033198,0.317688598578521]
>       (Iteration 3) Parametric Dispersion Coefs: [0.0687914737955971,0.286712544936312]
>       (Iteration 4) Parametric Dispersion Coefs: [0.0700139380668246,0.278453672742301]
>       (Iteration 5) Parametric Dispersion Coefs: [0.0703387772826443,0.276472033092631]
>       (FINAL) Parametric Dispersion Coefs: [0.0703685656436518,0.27626661272365]
>    fdf: Fitting splice-junction dispersions:
>       (Iteration 1) Parametric Dispersion Coefs: [0.10891582064228,0.165875588637397]
>       (Iteration 2) Parametric Dispersion Coefs: [0.171103339868573,0.0341692236351757]
Error : parametric dispersion fit failed
In addition: Warning message:
In adapted.estimateDispersionsFit(means = means[useForFit], disps = disps[useForFit],  :
  the parametric fit of dispersion estimates over the mean of counts
failed, which occurs when the trend is not well captured by the
```

Thanks!

**Comment by hartleys** [comment]
Is this running with method.fitDisp set to "local"?

**Comment by sahilseth** [comment]
I updated to the latest version this morning, and have started again; will see.. Since DEXSeq had also failed, may it is something with the data?

**Comment by hartleys** [comment]
Can you post the exact commands you used, along with the full log?

**Comment by sahilseth** [comment]
Here are some details:
[junctionseq_logs.txt](https://github.com/hartleys/JunctionSeq/files/39241/junctionseq_logs.txt)

**Comment by hartleys** [comment]
According to the logs these were run yesterday, and the log formatting
matches the older version of JunctionSeq.

Do you have the logs from the most recent version?

**Comment by sahilseth** [comment]
Yes, these are from yesterday, todays run is still in process; would take a little while before we get that error. 

On November 19, 2015 at 11:40:37 AM, hartleys (notifications@github.com) wrote:

According to the logs these were run yesterday, and the log formatting
matches the older version of JunctionSeq.

Do you have the logs from the most recent version?
On Nov 19, 2015 12:23 PM, "sseth" notifications@github.com wrote:

> Here are some details:
> junctionseq_logs.txt
> https://github.com/hartleys/JunctionSeq/files/39241/junctionseq_logs.txt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hartleys/JunctionSeq/issues/3#issuecomment-158126554.
> 
> —
> Reply to this email directly or view it on GitHub.

-- 

Sent with Airmail

**Comment by hartleys** [comment]
Ah ok. I misunderstood.

Let me know how it goes.

**Comment by sahilseth** [comment]
Btw, seems its passed the step which failed last time?

using supplied model matrix
using supplied model matrix
using supplied model matrix
-----> ejsd: Dispersion estimation failed for 0 out of 396493 'testable' counting bins. Setting these features to be 'untestable'
---> FINISHED estimateJunctionSeqDispersions (Thu Nov 19 08:54:13 2015)

> rJSA: Dispersions estimated. Thu Nov 19 08:54:13 2015.
> rJSA: Fitting Dispersion Fcn... Thu Nov 19 08:54:14 2015.
> fitDispersionFunction() Starting (Thu Nov 19 08:54:14 2015)
>   (fitType = local)
>   (finalDispersionMethod = shrink)
>   (fitDispersionsForExonsAndJunctionsSeparately = TRUE)
> min(means[useForFit], na.rm=T)=0.012191905482834
>    fdf: Fitting dispersions:
>    fdf: Fitting dispersions of exons and junctions to separate fitted trends.
>    fdf: Fitting exon dispersions:
>    fdf: Fitting splice-junction dispersions:
> fdf(): 'Shrinking' fitted and feature-specific dispersion estimates.

On November 19, 2015 at 5:01:38 PM, hartleys (notifications@github.com) wrote:

Ah ok. I misunderstood.

—
Reply to this email directly or view it on GitHub.

-- 

Sent with Airmail

**Comment by sahilseth** [comment]
Looks like we went past the previous error; but had issues with testJunctionsForDiffUsage.

```
> fdf() Dispersion estimate failed for 0 out of 396493 features.
> fitDispersionFunction() Done. (Thu Nov 19 13:19:12 2015)
> rJSA: Dispersions Fcn Fitted. Thu Nov 19 13:19:12 2015.
> rJSA: Testing for DEU... Thu Nov 19 13:19:12 2015.
    [[Using package "BiocParallel" for parallelization. (Using 10 cores)]]
-------> testJunctionsForDiffUsage: Starting hypothesis test iteration. (Thu Nov 19 13:34:10 2015)
Error in unserialize(socklist[[n]]) : error reading from connection

> Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Error in serialize(data, node$con, xdr = FALSE) :
  error writing to connection
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Error in serialize(data, node$con, xdr = FALSE) :
  error writing to connection
Error in serialize(data, node$con, xdr = FALSE) :
  error writing to connection
```

Looks like it had issues reading the file. If you have seen this before, ideas? Otherwise I will try running this on a different server to rule those issues out.

**Comment by hartleys** [comment]
Woah. That looks more like a technical problem. Never seen anything like
that before.

I would try running the analysis step by step. After each step, save the
JunctionSeqCountSet object using the command:

save(jscs, file = "jscs.stepX.RData")

You can then reload it with:
load("jscs.stepX.RData")

That way you don't have to redo everything each time.

I would be interested to see your dispersion plot and maybe your MA plot.
Your dataset seems unusual.
