### ISSUE TITLE
Estimated runtime and progress indicator

### ISSUE THREAD

**Issue by mebbert** [hartleys/JunctionSeq#30]
Hi,

I started a JunctionSeq job using 5 cores (reserving 20G per core) on a set of 120 RNASeq samples (human) last Wednesday (January 10, 2018) that is still running (approaching 5 full days). Each core is currently consuming ~16.5G RAM. 

Questions:
1. Any idea how long it should take? 
2. Would it be difficult to add a progress indicator to the output? It has been on the following step since day 1: `Executing DESeq2 call: estimateUnsharedDispersions`.

Really appreciate it.

**Comment by mebbert** [comment]
I restarted the job giving 32 cores and 700G or RAM. It "finished" (with an error) in ~12 hours. That sort of answers question 1. Just need to figure out the error.

I'll leave the question open as a feature request for a progress indicator.

**Comment by hartleys** [comment]
Use the debug.mode parameter. This should add more progress info.

**Comment by mebbert** [comment]
I didn't see much more of a progress indicator with `debug.mode = TRUE`. Maybe worth revisiting in a future version.
