### ISSUE TITLE
How can I write all results to JunctionSeq Object (jscs data) in R ?

### ISSUE THREAD

**Issue by kaanokay** [hartleys/JunctionSeq#41]
Hello Dr. Hartley,

I have a problem about manipulation of JunctionSeq's outcome.

writeCompleteResults function writes all results as the folder, but I want write these results to jcsc data in R and then I will manipulate jscs data to make different analysis. 
I need pvalue, padj and logFC values of each exon and writeCompleteResults function provide that but these results record in my pc as the folder, but not in R.
DEXSeq provide a function called DEXSeqResults that write all results to DEXSeq object, but I couldn't find any function that provide such thing for JunctionSeq.
I can't manipulate results of writeCompleteResults in R, after I transfer it from my folder to R.
How can I write all results jscs data like writeCompleteResults function make.

Thank you.

**Comment by hartleys** [comment]
To save any R object use the 'save' command, which is a base function of R:

    save(jscs, file = "my/output/directory/my.savefile.Rdata");

Then load it again with:

    load("my/output/directory/my.savefile.Rdata");
