### ISSUE TITLE
Error: C stack usage  50949656 is too close to the limit"

### ISSUE THREAD

**Issue by CS791** [hartleys/JunctionSeq#47]
Hi!

I got an error:

"> jscs2 <- runJunctionSeqAnalyses(sample.files = countFiles,
+                                 sample.names = decoder$sample.ID,
+                                 condition=factor(decoder$group.ID),
+                                 flat.gff.file = gff.file, nCores = 1, analysis.type = "junctionsAndExons")
> STARTING runJunctionSeqAnalyses (v1.16.0) (Sun Apr 19 13:38:59 2020)
> rJSA: sample.files:  cts/Col_22C/QC.spliceJunctionAndExonCounts.withNovel.forJunctionSeq.txt.gz
> rJSA: sample.names:  Col_4C, Col_22C
> rJSA: condition:  CASE, CTRL
> rJSA: analysis.type:  junctionsAndExons
> rJSA: use.junctions:  TRUE
> rJSA: use.novel.junctions:  TRUE
> rJSA: use.exons:  TRUE
> rJSA: nCores:  1
> rJSA: use.covars:  
> rJSA: test.formula0:  ~ sample + countbin
> rJSA: test.formula1:  ~ sample + countbin + condition:countbin
> rJSA: use.multigene.aggregates:  FALSE
> rJSA: Reading Count files... Sun Apr 19 13:38:59 2020.
-> STARTING readJunctionSeqCounts (Sun Apr 19 13:38:59 2020)
---> RJSC; (v1.16.0)
---> RJSC: samplenames: Col_4C,Col_22C
Error: C stack usage  50949656 is too close to the limit"

Any help is much appreciated.

Thanks
SC

**Comment by hartleys** [comment]
That looks kinda like an out of memory error getting thrown by the C
compiled side of DESeq. What machine are you using and how big is your
dataset? Would it be possible to run it with more memory available?

**Comment by CS791** [comment]
I am using Linux 64 bit, with 32 G memory. 
My dataset is not big, I am working on Arabidopsis with two samples. 

Thank you
SC

**Comment by CS791** [comment]
Thank you for your reply. 
I got rid of the following error:
"Error: C stack usage 50949656 is too close to the limit",

However, I got another issue while running Junctionseq:

" jscs <- runJunctionSeqAnalyses(sample.files = countFiles, 
+                                sample.names = decoder$sample.ID, 
+                                condition=factor(decoder$group.ID), 
+                                flat.gff.file = gff.file, nCores = 1, 
+                                analysis.type = "junctionsAndExons" )
> STARTING runJunctionSeqAnalyses (v1.16.0) (Fri Apr 24 11:36:30 2020)
> rJSA: sample.files:  cts/Col_4C/QC.spliceJunctionAndExonCounts.withNovel.forJunctionSeq.txt.gz, cts/Col_22C/QC.spliceJunctionAndExonCounts.withNovel.forJunctionSeq.txt.gz
> rJSA: sample.names:  Col_4C, Col_22C
> rJSA: condition:  CASE, CTRL
> rJSA: analysis.type:  junctionsAndExons
> rJSA: use.junctions:  TRUE
> rJSA: use.novel.junctions:  TRUE
> rJSA: use.exons:  TRUE
> rJSA: nCores:  1
> rJSA: use.covars:  
> rJSA: test.formula0:  ~ sample + countbin
> rJSA: test.formula1:  ~ sample + countbin + condition:countbin
> rJSA: use.multigene.aggregates:  FALSE
> rJSA: Reading Count files... Fri Apr 24 11:36:30 2020.
-> STARTING readJunctionSeqCounts (Fri Apr 24 11:36:30 2020)
---> RJSC; (v1.16.0)
---> RJSC: samplenames: Col_4C,Col_22C
---> RJSC: flat.gff.file: cts/withNovel.forJunctionSeq.gff.gz
---> RJSC: use.exons:TRUE
---> RJSC: use.junctions:TRUE
---> RJSC: use.novel.junctions:TRUE
---> File read complete.
---> Extracted counts. Found 379653 features so far.
---> Extracted gene-level counts. Found: 32012 genes and aggregate-genes.
---> Removed gene features. Found: 347641 features to be included so far.
---> Note: 18710 counting bins from overlapping genes
--->          There are 760 multigene aggregates.
--->          There are 1581 genes that are part of an aggregate.
---> Removed multigene-aggregate features. Found: 328931 features to be included so far.
---> Final feature count: 328931 features to be included in the analysis.
---> Extracted feature counts.
---> counts complete.
-----> reading annotation...
-----> formatting annotation...
-----> initial generation...
-----> creating jscs...
-----> generating count vectors... (Fri Apr 24 11:36:46 2020)
> Using single-core execution.
    getAllJunctionSeqCountVectors: dim(counts) = 328931,2 (Fri Apr 24 11:36:46 2020)
    getAllJunctionSeqCountVectors: dim(gct) = 32012,2
    getAllJunctionSeqCountVectors: out generated. dim = 328931,4 (Fri Apr 24 11:36:48 2020)
-----> count vectors generated (Fri Apr 24 11:36:48 2020)
-----> generating DESeqDataSet... (Fri Apr 24 11:36:48 2020)
-----> DESeqDataSet generated (Fri Apr 24 11:36:48 2020)
> rJSA: Count files read. Fri Apr 24 11:36:48 2020.
> rJSA: Estimating Size Factors... Fri Apr 24 11:36:48 2020.
> rJSA: Size Factors Done. Size Factors are:.
> rJSA: Col_4C,Col_22C
> rJSA: 0.985389136248935,1.01482750642724
> rJSA: Estimating Dispersions... Fri Apr 24 11:36:48 2020.
---> STARTING estimateJunctionSeqDispersions: (v1.16.0) (Fri Apr 24 11:36:48 2020)
-----> ejsd: 273160 counting bins are marked 'testable'. across 18832 genes.
             (152104 exonic regions, 106250 known junctions, 14806 novel junctions)
---------> Executing DESeq2 call: estimateUnsharedDispersions
Error in estimateDispersionsGeneEst(x, maxit = maxit, quiet = quiet, modelMatrix = modelMatrix,  : 
  the number of samples and the number of model coefficients are equal,
  i.e., there are no replicates to estimate the dispersion.
  use an alternate design formula"

I am not sure where I am making mistake:

Thank you

SC

**Comment by hartleys** [comment]
JunctionSeq is basically an extension of DEXSeq, and both tools require
multiple biological replicates in order to calculate the dispersion.

Right now at least it doesnt support 1v1 comparisons. Honestly at that
point I would just look for extreme outlier differentials just by loading
the counts and comparing them directly in R.

But you wont be able to assign a p-value. Its fundamentally not possible to
get a truly valid p-value without replicates.

**Comment by CS791** [comment]
Thank you for your response and help. 
Yes, you are right, I made mistake at QoRTs level, where I merged Biological replicates as well.
Now it is working fine. 
I am going to use a large number of samples around 8 with biological replicates.
Please do let me know if you have any suggestions.

Thank you again for your help.

Kind regards
SC
