### ISSUE TITLE
to  get differentially expressed genes

### ISSUE THREAD

**Issue by genomaths** [hartleys/JunctionSeq#8]
A gene could not be differentially expressed and still some exons and junctions could be differentially used and vice versa. Could you please tell me how can I get the differentially expressed genes from the results of the function writeCompleteResults?

**Comment by hartleys** [comment]
JunctionSeq only searches for differential usage of exons and junctions. It does not
search for gene level differential expression.

Doing so would basically involve a separate model framework and dispersion
estimation and fit. It would be equivalent to just running a separate DE
analysis with DESeq2.

To test for overall differential gene expression, I recommend using a tool
designed for that specific purpose, such as DESeq2 or EdgeR.

For more information on how to do that, see the "comprehensive walkthrough"
document, here:

http://hartleys.github.io/JunctionSeq/

**Comment by genomaths** [comment]
Thanks Hartley
